let data=[],category='Todos',page=0;const size=16,$=s=>document.querySelector(s);const clean=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function title(p){return p.name===p.code?({'Fregaderos':'Fregadero con accesorios','Estaciones de carga e iluminación':'Estación de carga','Wall panels y molduras':p.code.startsWith('WP')?'Wall panel':'Moldura decorativa','Accesorios de cocina':'Accesorio de cocina','Herrajes para clóset':'Herraje para clóset'}[p.category]||p.category):p.name}
function select(c){category=c;page=0;render()}
function render(){const q=clean($('#search').value);const list=data.filter(p=>(category==='Todos'||p.category===category)&&clean(p.code+' '+title(p)+' '+p.details+' '+p.category).includes(q));const pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages-1);$('#count').textContent=list.length+' productos · '+category;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===category);b.setAttribute('aria-pressed',b.dataset.filter===category)});$('#products').innerHTML=list.slice(page*size,(page+1)*size).map(p=>`<button class="product" data-code="${escape(p.code)}"><div class="product-image">${p.image?`<img loading="lazy" src="${escape(p.image)}" alt="${escape(title(p)+' '+p.code)}">`:'<span>Imagen no disponible</span>'}</div><small>${escape(p.code)}</small><h3>${escape(title(p))}</h3><p>${escape(p.category)}</p></button>`).join('')||'<p class="empty">No encontramos productos con esa búsqueda. Prueba con otro nombre o código.</p>';$('#previous').disabled=page===0;$('#next').disabled=page===pages-1;$('#page-label').textContent=`Página ${page+1} de ${pages}`;document.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>openProduct(b.dataset.code))}
function openProduct(code){const p=data.find(p=>p.code===code);$('#detail-content').innerHTML=`${p.image?`<img src="${escape(p.image)}" alt="${escape(title(p))}">`:'<div class="product-image">Imagen no disponible</div>'}<div><small>${escape(p.category)} · ${escape(p.code)}</small><h2>${escape(title(p))}</h2><p>${escape(p.details)}</p><a class="button" href="https://www.instagram.com/posh.herrajes/" target="_blank" rel="noopener">Consultar disponibilidad</a></div>`;$('#detail').showModal()}
$('#close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};$('#search').oninput=()=>{page=0;render()};$('#reset').onclick=()=>{$('#search').value='';select('Todos')};$('#previous').onclick=()=>{page--;render();$('#catalogo').scrollIntoView()};$('#next').onclick=()=>{page++;render();$('#catalogo').scrollIntoView()};document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>select(a.dataset.category));Promise.resolve(JSON.parse($('#catalog-data').textContent)).then(d=>{data=d;const cats=['Todos',...new Set(data.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button data-filter="${escape(c)}" aria-pressed="false">${escape(c)}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>select(b.dataset.filter));render()}).catch(()=>{$('#products').innerHTML='<p class="empty">No pudimos cargar el catálogo. Actualiza la página para volver a intentarlo.</p>'});

// Consultas generales y por producto.
function whatsappUrl(number,message){const digits=String(number||'').replace(/\D/g,'');return /^\d{8,15}$/.test(digits)?`https://wa.me/${digits}?text=${encodeURIComponent(message)}`:null}
function consultWhatsApp(code){const config=window.POSH_CONFIG||{};const message=code?`Hola POSH, quiero consultar disponibilidad y precio del producto ${code}.`:config.whatsappMessage||'Hola POSH, me gustaría consultar sus productos.';const url=whatsappUrl(config.whatsappNumber,message);if(url){window.open(url,'_blank','noopener,noreferrer')}else{$('#detail').close();$('#whatsapp-pending').showModal()}}
$('#whatsapp-open').onclick=()=>consultWhatsApp();$('#whatsapp-close').onclick=()=>$('#whatsapp-pending').close();
const originalOpenProduct=openProduct;openProduct=function(code){originalOpenProduct(code);const b=document.createElement('button');b.className='button whatsapp-product';b.textContent='Consultar por WhatsApp';b.onclick=()=>consultWhatsApp(code);$('#detail-content>div:last-child').append(b)};
